# Generated by Django 5.0.6 on 2024-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_geodepartment_surface_km2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocommune',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='geocommune',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
