# Generated by Django 5.0.6 on 2024-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_geocommune_uuid_alter_geodepartment_uuid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userusergroup",
            constraint=models.UniqueConstraint(
                fields=("user", "user_group"), name="user_user_group_unique"
            ),
        ),
    ]
