# Generated by Django 5.0.6 on 2024-06-04 08:16

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_userusergroup_user_user_group_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=1024, unique=True)),
                (
                    "tile_set_status",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("VISIBLE", "VISIBLE"),
                                ("HIDDEN", "HIDDEN"),
                                ("DEACTIVATED", "DEACTIVATED"),
                            ],
                            max_length=255,
                        ),
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
