# Generated by Django 5.0.6 on 2024-06-04 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_tileset"),
    ]

    operations = [
        migrations.AddField(
            model_name="tileset",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
