# Generated by Django 5.0.6 on 2024-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_tileset_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileset",
            name="tile_set_status",
            field=models.CharField(
                choices=[
                    ("VISIBLE", "VISIBLE"),
                    ("HIDDEN", "HIDDEN"),
                    ("DEACTIVATED", "DEACTIVATED"),
                ],
                max_length=255,
            ),
        ),
    ]
