# Generated by Django 5.0.6 on 2024-06-06 15:44

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_tileset_tile_set_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("address", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_objects",
                        to="core.objecttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetectionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "detection_control_status",
                    models.CharField(
                        choices=[
                            ("NO_CONTROL", "NO_CONTROL"),
                            ("SIGNALED_INTERNALLY", "SIGNALED_INTERNALLY"),
                            ("SIGNALED_COLLECTIVITY", "SIGNALED_COLLECTIVITY"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "detection_validation_status",
                    models.CharField(
                        choices=[
                            ("SUSPECT", "SUSPECT"),
                            ("LEGITIMATE", "LEGITIMATE"),
                            ("INVALIDATED", "INVALIDATED"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user_last_update_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_datas_last_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "detection_source",
                    models.CharField(
                        choices=[
                            ("INTERFACE_DRAWN", "INTERFACE_DRAWN"),
                            ("ANALYSIS", "ANALYSIS"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "detected_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="core.detectedobject",
                    ),
                ),
                (
                    "detection_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection",
                        to="core.detectiondata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
