# Generated by Django 5.0.6 on 2024-06-10 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_detectedobject_detectiondata_detection"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DetectedObject",
            new_name="DetectionObject",
        ),
    ]
