# Generated by Django 5.0.6 on 2024-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_rename_detectedobject_detectionobject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="detected_object",
            new_name="detection_object",
        ),
        migrations.RenameField(
            model_name="detectiondata",
            old_name="user_last_update_user_id",
            new_name="user_last_update_user",
        ),
    ]
