# Generated by Django 5.0.6 on 2024-06-10 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_rename_detected_object_detection_detection_object_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="detection_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detection",
                to="core.detectiondata",
            ),
        ),
        migrations.AlterField(
            model_name="detection",
            name="score",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ]
            ),
        ),
    ]
