# Generated by Django 5.0.6 on 2024-06-11 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_detectionobject_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detectiondata",
            old_name="user_last_update_user",
            new_name="user_last_update",
        ),
    ]
