# Generated by Django 5.0.6 on 2024-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_tileset_tile_set_scheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="tileset",
            name="tile_set_type",
            field=models.CharField(
                choices=[
                    ("BACKGROUND", "BACKGROUND"),
                    ("PARTIAL", "PARTIAL"),
                    ("INDICATIVE", "INDICATIVE"),
                ],
                default="BACKGROUND",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
