# Generated by Django 5.0.6 on 2024-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_tileset_tile_set_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileset",
            name="tile_set_scheme",
            field=models.CharField(
                choices=[("tms", "tms"), ("xyz", "xyz")], max_length=255, null=True
            ),
        ),
    ]
