# Generated by Django 5.0.6 on 2024-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_tileset_tile_set_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileset",
            name="tile_set_scheme",
            field=models.CharField(
                choices=[("tms", "tms"), ("xyz", "xyz")], default="xyz", max_length=255
            ),
            preserve_default=False,
        ),
    ]
