# Generated by Django 5.0.6 on 2024-06-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_tile_tile_xyz_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="tile",
            field=models.ForeignKey(
                default=94,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="core.tile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detection",
            name="tile_set",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="core.tileset",
            ),
            preserve_default=False,
        ),
    ]
