# Generated by Django 5.0.6 on 2024-06-19 13:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_detection_tile_detection_tile_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileset",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True, srid=4326
            ),
        ),
    ]
