# Generated by Django 5.0.6 on 2024-07-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_geozone_remove_geocommune_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geozone",
            name="name_normalized",
            field=models.CharField(default="occitanie", max_length=255),
            preserve_default=False,
        ),
    ]
