# Generated by Django 5.0.6 on 2024-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_detectionobject_parcel_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["score"], name="core_detect_score_48a965_idx"),
        ),
    ]
