# Generated by Django 5.0.6 on 2024-07-12 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_detection_auto_prescribed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="prescription_duration_years",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
