# Generated by Django 5.0.6 on 2024-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_alter_detectiondata_detection_control_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="batch_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="detectionobject",
            name="batch_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
