# Generated by Django 5.0.6 on 2024-07-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_detection_batch_id_detectionobject_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectiondata",
            name="user_last_update",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detection_datas_last_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
