# Generated by Django 5.0.6 on 2024-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_detectiondata_user_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="tileset",
            name="last_import_ended_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tileset",
            name="last_import_started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
