# Generated by Django 5.0.6 on 2024-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_tileset_last_import_ended_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="import_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="detectionobject",
            name="import_id",
            field=models.IntegerField(null=True),
        ),
    ]
