# Generated by Django 5.0.6 on 2024-07-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_detection_import_id_detectionobject_import_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objecttypecategory",
            name="object_types",
        ),
        migrations.CreateModel(
            name="ObjectTypeCategoryObjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type_category_object_type_status",
                    models.CharField(
                        choices=[("VISIBLE", "VISIBLE"), ("HIDDEN", "HIDDEN")],
                        max_length=255,
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_type_category_object_types",
                        to="core.objecttype",
                    ),
                ),
                (
                    "object_type_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_type_category_object_types",
                        to="core.objecttypecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
