# Generated by Django 5.0.6 on 2024-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_detection_core_detect_detecti_586850_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocustomzone",
            name="color",
            field=models.CharField(default="#ff0000", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
