# Generated by Django 5.0.6 on 2024-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_geocustomzone_geo_custom_zone_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="detection",
            new_name="detection_uuid_idx",
            old_name="core_detect_uuid_ecc8f4_idx",
        ),
        migrations.RenameIndex(
            model_name="objecttype",
            new_name="objecttype_uuid_idx",
            old_name="core_object_uuid_e9c1f7_idx",
        ),
        migrations.RenameIndex(
            model_name="tileset",
            new_name="tileset_uuid_idx",
            old_name="core_tilese_uuid_322dea_idx",
        ),
        migrations.AddIndex(
            model_name="detectiondata",
            index=models.Index(fields=["uuid"], name="detectiondata_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="detectionobject",
            index=models.Index(fields=["uuid"], name="detectionobject_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="geozone",
            index=models.Index(fields=["uuid"], name="geozone_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="objecttypecategory",
            index=models.Index(fields=["uuid"], name="objecttypecategory_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(fields=["uuid"], name="parcel_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(fields=["uuid"], name="usergroup_uuid_idx"),
        ),
    ]
