# Generated by Django 5.0.6 on 2024-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_alter_geozone_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionobject",
            name="geo_custom_zones",
            field=models.ManyToManyField(
                related_name="detection_objects", to="core.geocustomzone"
            ),
        ),
    ]
