# Generated by Django 5.0.6 on 2024-09-03 08:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_detectionobject_geo_custom_zones"),
    ]

    operations = [
        migrations.AddField(
            model_name="geocustomzone",
            name="geometry_simplified",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True, srid=4326
            ),
        ),
    ]
