# Generated by Django 5.0.6 on 2024-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_geocustomzone_geometry_simplified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geocustomzone",
            name="geometry_simplified",
        ),
    ]
