# Generated by Django 5.0.6 on 2024-09-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_remove_geocustomzone_geometry_simplified"),
    ]

    operations = [
        migrations.AddField(
            model_name="tileset",
            name="monochrome",
            field=models.BooleanField(default=False),
        ),
    ]
