# Generated by Django 5.0.6 on 2024-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_tileset_monochrome"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionobject",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="id_parcellaire",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
