# Generated by Django 5.0.6 on 2024-10-01 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_usergroup_custom_geo_zones"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usergroup",
            old_name="custom_geo_zones",
            new_name="geo_custom_zones",
        ),
    ]
