# Generated by Django 5.0.6 on 2024-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_rename_custom_geo_zones_usergroup_geo_custom_zones"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_detectiondata SET detection_validation_status = 'LEGITIMATE', detection_control_status = 'REHABILITATED' WHERE detection_validation_status = 'DISAPPEARED'",
        ),
        migrations.AlterField(
            model_name="detectiondata",
            name="detection_validation_status",
            field=models.CharField(
                choices=[
                    ("DETECTED_NOT_VERIFIED", "DETECTED_NOT_VERIFIED"),
                    ("SUSPECT", "SUSPECT"),
                    ("LEGITIMATE", "LEGITIMATE"),
                    ("INVALIDATED", "INVALIDATED"),
                ],
                max_length=255,
            ),
        ),
    ]
