# Generated by Django 5.0.6 on 2024-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_alter_detectiondata_detection_validation_status"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_detectiondata SET detection_control_status = 'NOT_CONTROLLED' WHERE detection_control_status = 'SIGNALED_INTERNALLY'",
        ),
        migrations.AlterField(
            model_name="detectiondata",
            name="detection_control_status",
            field=models.CharField(
                choices=[
                    ("NOT_CONTROLLED", "NOT_CONTROLLED"),
                    ("SIGNALED_COLLECTIVITY", "SIGNALED_COLLECTIVITY"),
                    ("SIGNALED_COMMUNE", "SIGNALED_COMMUNE"),
                    ("CONTROLLED_FIELD", "CONTROLLED_FIELD"),
                    ("PRIOR_LETTER_SENT", "PRIOR_LETTER_SENT"),
                    ("OFFICIAL_REPORT_DRAWN_UP", "OFFICIAL_REPORT_DRAWN_UP"),
                    ("OBSERVARTION_REPORT_REDACTED", "OBSERVARTION_REPORT_REDACTED"),
                    ("VERBALIZED", "VERBALIZED"),
                    ("REHABILITATED", "REHABILITATED"),
                ],
                max_length=255,
            ),
        ),
    ]
