# Generated by Django 5.0.6 on 2024-11-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_analyticlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticlog",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
